### PR TITLE
Verify file path is string before reading and rendering

### LINKED ISSUE #264: Uncaught TypeError: path must be a string
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1
**Thrown From**: [markdown-preview](https://github.com/atom/markdown-preview) package, v0.150.0

### Stack Trace

Uncaught TypeError: path must be a string

```
At fs.js:535

TypeError: path must be a string
  at TypeError (native)
  at Object.fs.open (fs.js:535:11)
  at Object.module.(anonymous function) [as open] (ATOM_SHELL_ASAR.js:144:20)
  at ReadStream.open (fs.js:1668:6)
  at new ReadStream (fs.js:1655:10)
  at Object.fs.createReadStream (fs.js:1610:10)
  at File.module.exports.File.read (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\pathwatcher\lib\file.js:286:27)
  at MarkdownPreviewView.module.exports.MarkdownPreviewView.getMarkdownSource (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\markdown-preview\lib\markdown-preview-view.js:246:26)
  at MarkdownPreviewView.module.exports.MarkdownPreviewView.renderMarkdown (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\markdown-preview\lib\markdown-preview-view.js:235:19)
  at MarkdownPreviewView.module.exports.MarkdownPreviewView.subscribeToFilePath (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\markdown-preview\lib\markdown-preview-view.js:88:19)
  at MarkdownPreviewView.module.exports.MarkdownPreviewView.attached (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\markdown-preview\lib\markdown-preview-view.js:49:23)
  at space-pen-div.View.element.attached (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:164:63)
  at space-pen-div.CustomElementPrototype.attachedCallback (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:51:55)
  at atom-pane.PaneElement.activeItemChanged (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\src\pane-element.js:150:24)
  at Emitter.module.exports.Emitter.emit (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\src\pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\src\pane.js:298:21)
  at tabs-tab.<anonymous> (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-ul.elemData.handle (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -3:10 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "SFTP-deployment",
      "ctags-status",
      "tree-view-open-files",
      "Remote-FTP",
      "coffee-compiler",
      "git-plus",
      "sass-compiler"
    ]
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.5.8
flex-tool-bar, v0.4.2
less-compiler, v0.6.2
linter, v1.0.6
open-recent, v2.2.4
project-manager, v1.15.10
project-view, v0.1.2
sass-autocompile, v0.7.1
symbols-tree-view, v0.9.3
tool-bar, v0.1.8
tool-bar-main, v0.0.8
tree-view-finder, v0.2.1
tree-view-git-status, v0.1.1

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by jlord**
This changes `getMarkdownSource` to first verify `@file` exists and then further check that the `path` it contains is a `string`. This should eliminate uncaught exceptions from trying to read files from paths that aren't strings.

Why aren't paths strings? To be continued... 

**todo**
- [x] add spec 

Closes #264

### CODE REVIEW

File: lib/main.coffee [hunk 1]
```diff
@@ -14,7 +14,9 @@ isMarkdownPreviewView = (object) ->
 atom.deserializers.add
   name: 'MarkdownPreviewView'
   deserialize: (state) ->
-    createMarkdownPreviewView(state) if state.constructor is Object
+    if state.constructor is Object
```
Comment (kevinsawicki) [inline lib/main.coffee]: I don't think this check is needed anymore, it was probably old and from when deserialization behaved differently.

File: lib/markdown-preview-view.coffee [hunk 2]
```diff
@@ -135,7 +135,7 @@ class MarkdownPreviewView extends ScrollView
     @getMarkdownSource().then (source) => @renderMarkdownText(source) if source?
 
   getMarkdownSource: ->
-    if @file?
+    if @file? and typeof @file.path is 'string'
```
Comment (kevinsawicki) [inline lib/markdown-preview-view.coffee]: This could be combined to just be:

```coffee
if @file?.getPath()
```

This should cover the null case.
