### PR TITLE
Fix "Save as HTML"

### LINKED ISSUE #70: Export CSS with HTML
Syntax themes can style the markdown preview using the `.markdown-preview` selector. I think when exporting a markdown preview to HTML, the necessary CSS to make the HTML file look the same as in atom should be embedded into the HTML.

This is especially true since one of the great benefits of markdown is that it can be so easily parsed and exported to different styles and formats - atom should make use of that power in my opinion.

### PR DESCRIPTION
**Pull request by ArnaudRinquin**
Generated HTML now contains `<pre>` code block instead of `atom-text-editor` and all required `css` is injected.

The CSS is taken from current editor syntaxe (`atom-text-editor`) and the package `.markdown-preview` stylesheets.

Fixes #70

### CODE REVIEW

**Comment by ArnaudRinquin** [comment]
Credits to @abe33 for the stylesheet extraction and @jrop for the inspiration.

**Comment by abe33** [comment]
Maybe someone from @atom/core can review this, it seems fine to me.

File: lib/markdown-preview-view.coffee [hunk 1]
```diff
@@ -177,6 +183,28 @@ class MarkdownPreviewView extends ScrollView
   getGrammar: ->
     @editor?.getGrammar()
 
+  getDocumentStyleSheets: -> # This function exists so we can stub it
```
Comment (nathansobo) [inline lib/markdown-preview-view.coffee]: One problem is that we won't always be loading the syntax theme style sheets into the global document context. We do that now only to support disabling the shadow DOM, which is something we're going to disable as soon as we have time. A better approach would be to get the styles out of an existing `atom-text-editor` element *or* create and attach an `<atom-styles context="atom-text-editor">` element and get the styles out of that. Sorry for the confusion. We really need to drop the global styles sooner rather than later.

**Comment by nathansobo** [comment]
This is super innovative and really cool. Really happy that you tested it thoroughly as well. My main concern is addressed in a comment regarding the use of `document` style sheets. I'm not sure that `document.styleSheets` includes style sheets that are attached inside of shadow roots. If I'm wrong about that and shadow style sheets are included, then this is good to go. But we better make sure.

**Comment by ArnaudRinquin** [comment]
Ok, I figured out another way to get the `atom-text-editor` style, right from a shadow die element. I'll ship that ASAP. Thanksmore the feedback.

**Comment by ArnaudRinquin** [comment]
@nathansobo Done!

For now, I expect an `atom-text-editor` to exist somewhere in the `document` but cases might happen where there is none (does it?). Not sure how to create one if there is none. Snippets welcomed if you feel that `atom-text-editor` creation is a requirement.

File: lib/markdown-preview-view.coffee (hunk 1 above)
Comment (ArnaudRinquin) [inline lib/markdown-preview-view.coffee]: Addressed in b4b1595e3b18c887322698ba12e4306bc2bd63e1

**Comment by nathansobo** [comment]
@ArnaudRinquin would you be willing to try one other approach... that of creating and attaching an `<atom-styles context="atom-text-editor"> element and grabbing the styles from there, then detaching? I do think it could be surprising for this not to work when no `atom-text-editor`s are present in the document.

**Comment by ArnaudRinquin** [comment]
@nathansobo I am not sure how to create and attach such an element.

I was going for something like:

```coffee
{TextEditorView} = require 'atom-space-pen-views'

# If needed...
textEditorView = new TextEditorView({mini: true})
$('body').append(textEditorView)

# get style...

textEditorView.detach()
```

**Comment by nathansobo** [comment]
Try something like this...

```coffee
textEditorStyles = document.createElement("atom-styles")
textEditorStyles.setAttribute "context", "atom-text-editor"
document.body.appendChild textEditorStyles
# get the stylesheets off the element
textEditorStyles.remove()
```

**Comment by ArnaudRinquin** [comment]
Thanks for for the hint, I tried something similar before without success but your snippet worked perfectly.

I think it is ready to ship.

**Comment by thedaniel** [comment]
One last nit to pick before this is merged: The `title` tag is set as 'Markdown to HTML' for every export. This should probably be something related to the content, like the filename, or perhaps the filename minus extension.

**Comment by ArnaudRinquin** [comment]
Done, using file name minus the extension with a fallback to `Markdown to HTML`.

**Comment by ArnaudRinquin** [comment]
The Travis build failed but that's weird. Tests run perfectly here and the last commit didn't change much anyway. Should we restart the Travis job?

**Comment by thedaniel** [comment]
Yeah, I kicked it off again. Looks like the failure was just Travis not being able to fetch the build script.

**Comment by thedaniel** [comment]
Worth a note that this applies only to "Save as HTML", not "Copy as HTML" which I think makes sense. We'll see if more issues come in for Copy as HTML and have that discussion then.

**Comment by jthuraisamy** [comment]
:+1:

**Comment by nickcmaynard** [comment]
Thank you @ArnaudRinquin!

**Comment by ArnaudRinquin** [comment]
My pleasure @nickcmaynard 

@thedaniel About the _Save/Copy as HTML_ we could clarify a bit more by renaming the menus:

* `Save as HTML page` or `Save as HTML document`
* `Copy as HTML markup`

**Comment by ArnaudRinquin** [comment]
This is actually broken, my bad, see #213.

**Comment by ChrisChinchilla** [comment]
I may be cross posting (https://github.com/atom/markdown-preview/issues/128) but this alludes to solving this issue. However, I don't see a 'save as html' option or am I missing something?

I would love to help resolve these issue(s) as atom markdown support is awesome… apart from the code export.
